/* Auto generated file by build command shell.
    !!!!!!!! Do not edit this file. !!!!!!!!
    Created time : Fri Oct 26 11:50:20 KST 2012
    Created by chero@pantech.com (GS1 Team)
*/
#ifndef BOARD_REV_H
#define BOARD_REV_H

/*
Current MODEL ID is T_EF44S 
LINUX Kernel Define & macro function is as follows
#define CONFIG_MACH_MSM8960_EF44S
machine_is_msm8960_ef44s() function
*/

#define PT10  0x01
#define WS10  0x02
#define WS15  0x04
#define WS20  0x08
#define TP10  0x10
#define TP20  0x20
#define TP30  0x40

#define BOARD_VER   TP20
#endif /*BOARD_REV_H*/
