/* Auto generated file by build command shell.
    !!!!!!!! Do not edit this file. !!!!!!!!
    Created time : Mon Apr 15 19:53:37 KST 2013
    Created by chero@pantech.com (GS1 Team)
*/
#ifndef BOARD_REV_H
#define BOARD_REV_H

#if defined(CONFIG_MACH_MSM8960_OSCAR)
#include "oscar/BOARD_REV.h"
#endif

#endif /*BOARD_REV_H*/
