/* Auto generated file by build command shell.
    !!!!!!!! Do not edit this file. !!!!!!!!
    Created time : Mon Apr 15 19:53:37 KST 2013
    Created by chero@pantech.com (GS1 Team)
*/
#ifndef BOARD_REV_H_OSCAR 
#define BOARD_REV_H_OSCAR 

/*
Current MODEL ID is T_OSCAR 
LINUX Kernel Define & macro function is as follows
#define CONFIG_MACH_MSM8960_OSCAR
machine_is_msm8960_oscar() function
*/

#define PT10  0x01
#define PT20  0x02
#define WS10  0x04
#define WS20  0x08
#define ES10  0x10
#define ES20  0x20
#define TP10  0x40
#define TP20  0x80

#define BOARD_VER   TP20
#endif /*BOARD_REV_H_OSCAR */
